name: evoman-comp
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - pandas
  - pygame
  - scipy
  - lapack # may be required for scipy
  - openblas # may be required for scipy
  - ipywidgets
  - jupyter
  - tqdm
  - deap
  - optuna
  - pip
  - pip:
      - neat-python